version: '3.1'

services:
  jtb-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "dev_jtb_db"
      MYSQL_USER: 'dev_jtb_db_user'
      MYSQL_PASSWORD: 'dev_jtb_db_password'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - '3306'
